spring:
  profiles:
  active: blue
  group:
    test: test
    local: local, common
    blue: blue, common
    green: green, common

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080
  serverAddress: 100.21.105.141

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
server:
  port: 8081
  serverAddress: 100.21.105.141

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enterprise_1
    username: sam
    password: Qwdf3696!
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddlAuto: update
server:
  port: 8080
  serverAddress: localhost

serverName: test_server

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rds-demo.cjykyawcgbun.us-west-2.rds.amazonaws.com/itsolution_core
    username: sam
    password: Qwdf3696!
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddlAuto: update

    showSql: true