spring:
  profiles:
    active: local
    group:
      test: test
      local: local
      blue: blue
      green: green

server:
  env: blue

---

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
  publicAddress: "http://localhost:8080"
serverName: local_server

logging:
  level:
    root: INFO


redirection:
  url:
    itSolution: "http://localhost:3000"
    sunriseCC: "http://localhost:4200"
s3:
  local:
    path: "C:\\Users\\samue\\Downloads\\"

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://ps-its.com/login/oauth2/code/google"
  servlet:
    multipart:
      location: "/home/ubuntu/temp/multipart"
server:
  port: 8080
  serverAddress: 44.242.115.211
  publicAddress: "http://ps-its.com"

serverName: blue_server

redirection:
  url:
    itSolution: "https://www.ps-its.com"
    sunriseCC: "https://sunrisechristcc.org"

s3:
  local:
    path: "/home/ubuntu/temp"

logging:
  level:
    root: INFO
---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://ps-its.com/login/oauth2/code/google"
  servlet:
    multipart:
      location: "/home/ubuntu/temp/multipart"
server:
  port: 8081
  serverAddress: 44.242.115.211
  publicAddress: "http://ps-its.com"
serverName: green_server

redirection:
  url:
    itSolution: "https://ps-its.com"
    sunriseCC: "https://sunrisechristcc.org/"

s3:
  local:
    path: "/home/ubuntu/temp"

logging:
  level:
    root: INFO