spring:
  profiles:
    active: local
    group:
      test: test
      local: local
      blue: blue
      green: green

server:
  env: blue

---

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080"
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
  publicAddress: "http://localhost:8080"
serverName: local_server




redirection:
  url:
    itSolution: "http://localhost:3000"
    sunriseCC: "http://localhost:4200"
s3:
  local:
    path: "C:\\Users\\samue\\Downloads\\"

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://itsolution.ps-its.com"
server:
  port: 8080
  serverAddress: 100.21.105.141
  publicAddress: "https://itsolution.ps-its.com"

serverName: blue_server

redirection:
  url:
    itSolution: "https://https://www.sangbeomyooportfolio.com/"
    sunriseCC: "https://https://sunrisechristcc.org/"

s3:
  local:
    path: "/home/ubuntu/"
---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://itsolution.ps-its.com"
server:
  port: 8081
  serverAddress: 100.21.105.141
  publicAddress: "https://itsolution.ps-its.com"
serverName: green_server

redirection:
  url:
    itSolution: "https://https://www.sangbeomyooportfolio.com/"
    sunriseCC: "https://https://sunrisechristcc.org/"

s3:
  local:
    path: "/home/ubuntu/"